#!/bin/zsh

alias imac='xrandr -s 3840x2160 && gsettings set org.gnome.desktop.interface text-scaling-factor 1.7 && gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 90'
alias dell='xrandr -s 1920x1080 && gsettings set org.gnome.desktop.interface text-scaling-factor 1.0 && gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 45'
alias sb='source ~/.zshrc'
alias norm='norminette | grep -v OK'

#addional
# set background
feh --bg-scale $HOME/Documents/w1.png

# opacity
if ! pgrep -x "picom" >/dev/null; then
  picom -b
fi

if [ -f /usr/bin/fastfetch ]; then
  fastfetch
fi
