#!/bin/zsh

# Aliases
alias imac='xrandr -s 3840x2160 && gsettings set org.gnome.desktop.interface text-scaling-factor 1.7 && gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 90'
alias dell='xrandr -s 1920x1080 && gsettings set org.gnome.desktop.interface text-scaling-factor 1.0 && gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 45'
alias sb='source ~/.zshrc'
alias norm='norminette | grep -v OK'

# Functions
lock()
{
    pkill ft_lock;
    LANG_MASK=$(xset -q | grep LED | awk '{ print $10 }')
    if [[ "$LANG_MASK" != "00000002" ]]; then 
      echo "Change lang to ENG first!"
      return 1
    fi
    echo -n "lock ? Y/n : ";
    read answer;
    if [[ "$answer" == "Y" || "$answer" == "y" ]]; then
        ft_lock
    fi
}

#addional
# set background
# use ./w1.png from current directory
# if it sshconnect to a remote server, it will not work
# let's check that first
#
#if [ -f /usr/bin/feh ]; then
#  feh --bg-scale ~/.myshells/personal/w1.png
#fi
# so now we will check two things if feh available and we are not ssh connected

if [ -f /usr/bin/feh ] && [ -z "$SSH_CLIENT" ]; then
  feh --bg-scale ~/.myshells/personal/w1.png
fi

# Question: why not use the full path to the image?
# Answer: because it is a relative path to the current directory 
# so if you run this script from another directory, it will not work
# Qestion: in develeoper therm what we call the ssh connection and reall connection (tty and pty)
# Answer: ssh connection is a remote connection and real connection is a local connection

# opacity
if [ -f /usr/bin/picom ] && [! pgrep -x "picom" >/dev/null]; then
  picom -b
fi

if [ -f /usr/bin/fastfetch ]; then
  fastfetch
fi

# Node: this packages required in this script
# sudo pacman -S feh picom fastfetch
